---
- name: Create AWS EC2
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: import keypair
    amazon.aws.ec2_key:
      name: ec2-user
      key_material: "{{ lookup('file', '/home/asnell/.ssh/id_rsa.pub') }}"
    tags:
      - ec2_create
      - ec2_keypair

  - name: launch new instance + user data
    amazon.aws.ec2_instance:
      name: aws_rh_httpd_vm
      region: us-east-2
      key_name: ec2-user
      instance_type: t3.micro
      security_group: ssh-web
      vpc_subnet_id: subnet-018350f9091326f7b
      network:
        assign_public_ip: true
        delete_on_termination: true
      image_id: ami-0f6c1051253397fef
      user_data: "{{ lookup('file', 'user_data.sh') }}"
      volumes: 
        - device_name: /dev/sda
          ebs: 
            volume_size: 8
            volume_type: gp2
            delete_on_termination: true
    tags:
      - ec2_create

