# tasks file for create_ec2
---
- name: import keypair
  amazon.aws.ec2_key:
    name: "{{ user_name }}"
    key_material: "{{ lookup('file', 'aws_id_rsa.pub') }}"
  tags:
    - ec2_create
    - ec2_keypair

- name: launch new instance + user data
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    region: "{{ aws_region }}"
    key_name: "{{ user_name }}"
    instance_type: "{{ inst_type }}"
    security_group: "{{ sec_grp }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    network:
      assign_public_ip: true
      delete_on_termination: true
    image_id: "{{ ami_image_id }}"
    user_data: "{{ lookup('file', 'user_data.sh') }}"
    volumes: 
      - device_name: /dev/sda
        ebs: 
          volume_size: 8
          volume_type: gp2
          delete_on_termination: true
  tags:
    - ec2_create

